version: '3.7'

services:
  db:
    image: mongo
#    entrypoint: ["/usr/bin/mongod", "--journal", "--bind_ip", "0.0.0.0", "--auth"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ROOTUSER}
      MONGO_INITDB_ROOT_PASSWORD: ${ROOTPASSWORD}
    command: [--auth]
    ports:
      - target: 27017
        published: 27017
        mode: host
    volumes:
      - mongo_data:/data/db
      - /data/mongo_config/:/data/configdb
    networks:
      - backend
    configs:
      - mongo-healthcheck
    healthcheck:
      test: ["CMD", "bash", "/mongo-healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 1m30s
      resources:
        limits:
          cpus: '8'
          memory: 12G

  express:
    image: mongo-express
    ports:
      - target: 8081
        published: 8081
        mode: host
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ROOTUSER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ROOTPASSWORD}
      ME_CONFIG_MONGODB_SERVER: 45.148.31.135

configs:
  # to avoid changes to the original mongo image, we import the healthcheck script using configs
  mongo-healthcheck:
    file: mongo-healthcheck

volumes:
  mongo_data:

networks:
  backend:
    external: true

