version: '3.7'

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${ROOTPASSWORD}
    command: [--auth]
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    configs:
      # to avoid changes to the original mongo image, we import the healthcheck script using configs
      - mongo-healthcheck
    healthcheck:
      test: ["CMD", "bash", "/mongo-healthcheck"]
      interval: 1m
      timeout: 10s
      retries: 3
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo == master

configs:
  # to avoid changes to the original mongo image, we import the healthcheck script using configs
  mongo-healthcheck:
    file: mongo-healthcheck

volumes:
  data:

networks:
  default:
    external:
      name: backend

