version: '3.7'

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${ROOTPASSWORD}
    command: [--auth]
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.mongo == master

volumes:
  data:
    driver: local
    driver_opts:
      device: "/data/mongo"

