# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      ROOTPASSWORD: ${{ secrets.MONGODB_ROOTPASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Docker Deployment
        # You may pin to the exact commit or the version.
        # uses: wshihadeh/docker-deployment-action@e11d221fc27fa0aca5bdd09b8d17f816c55d6705
        uses: wshihadeh/docker-deployment-action@v2
        with:
          # Remote Docker host ie (user@host)
          remote_docker_host: deployer@master01.vps.webdock.io
          # Remote Docker SSH public key
          ssh_public_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          # SSH private key used to connect to the docker host
          ssh_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          # Deployment command args.
          args: mongo
          # Deployment mode either docker-swarm or docker-compose. Default is docker-compose.
          deployment_mode: docker-swarm
          # Docker stack file used. Default is docker-compose.yaml
          stack_file_name:  docker-compose.yml

